version: '3.1'
services:
  zookeeper:
    container_name: the-red-zookeeper
    image: zookeeper
    ports:
      - "2181:2181"
  zk-web:
    container_name: the-red-zk-web
    image: goodguide/zk-web
    ports:
      - "18081:8080"
    environment:
      - ZKWEB_PORT=8080
      - ZKWEB_CREDENTIALS=admin:the_red
  the_red_redis_queue_primary:
    image: redis:6.0.6
    hostname: localhost
    ports:
    - 16379:6379
    container_name: the_red_redis_queue_primary
  the_red_redis_queue_replica:
    image: redis:6.0.6
    hostname: localhost
    ports:
    - 16380:6379
    container_name: the_red_redis_queue_replica
  the_red_sidekiq:
    image: ascensionit/sidekiq-web
    hostname: localhost
    container_name: the_red_sidekiq
    environment:
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 7379
    network_mode: "host"
  the_red_mysql:
    build:
      context: .
      dockerfile: mysql_dockerfile
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: the_red#
      MYSQL_USER: the_red
      MYSQL_PASSWORD: the_red#
      MYSQL_DATABASE: the_red
    ports:
    - 13306:3306
    container_name: the_red_mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
