version: '3.1'
services:
  the_red_redis_1:
    image: redis:6.0.6
    hostname: localhost
    ports:
    - 16380:6379
  the_red_redis_2:
    image: redis:6.0.6
    hostname: localhost
    ports:
    - 16381:6379
  the_red_redis_3:
    image: redis:6.0.6
    hostname: localhost
    ports:
    - 16382:6379
  the_red_redis_queue_primary:
    image: redis:6.0.6
    hostname: localhost
    ports:
    - 16379:6379
  the_red_sidekiq:
    image: ascensionit/sidekiq-web
    hostname: localhost
    container_name: the_red_sidekiq
    environment:
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 16379
  the_red_mysql:
    build:
      context: .
      dockerfile: mysql_dockerfile
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: the_red#
      MYSQL_USER: the_red
      MYSQL_PASSWORD: the_red#
      MYSQL_DATABASE: the_red
    ports:
    - 13306:3306
    container_name: the_red_mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
